apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-git-clone
spec:
  taskRef:
    name: git-clone
  workspaces:
    - name: output
      persistentVolumeClaim:
      claimName: tkn-pvc
  params:
  - name: url
    value: https://github.com/mohamedmatrouh/hello-world-example.git
  - name: revision
    value: main
