apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-npm-install-cache
  annotations:
    description: |
      Task to check if we need to run npm install
spec:
  params:
    - name: PATH_CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
  workspaces:
    - name: source
    - name: cache
  results:
    - name: output
      description: Result of the task
  steps:
    - name: check
      image: ubuntu:20.04
      script: |
      
        cd $(workspaces.source.path)/$(params.PATH_CONTEXT)

        CASH_FOLDER=$(workspaces.cache.path)

        saveFileHashToCache(){
            local fileName=$1
            sha1sum $fileName > $CASH_FOLDER/"$fileName.sha1"
        }

        loadFileHashFromCache(){
            local fileName=$1
            if [ -f $CASH_FOLDER/"$fileName.sha1" ]; then
                cat $CASH_FOLDER/"$fileName.sha1"
            fi
        }


        checkIfFilesHaveChanged() {

            local files=("$@")
            local counter=0
            for fileName in "${files[@]}";
                do
                    echo "checking $fileName.... "

                    local oldHash=$(loadFileHashFromCache $fileName)
                    local newHash=$(sha1sum $fileName)

                    if [ "$oldHash" == "$newHash" ]; then
                        echo "No changes detected for $fileName"
                    else
                        echo "Changes detected for $fileName"
                        saveFileHashToCache $fileName
                        ((counter = counter + 1))
                    fi

                done
                
            if [ "$counter" == 0 ]; then
                exitFromTask 0
            else
                exitFromTask 1
            fi
        }

        exitFromTask() {
            if [ "$1" == 0 ]; then
                printf "true" | tee $(results.output.path)
            else
                printf "false" | tee $(results.output.path)
            fi
            
            exit 0;
        }

        checkIfFilesHaveChanged package.json package-lock.json
