apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-npm-install
  annotations:
    description: |
      Task to check if we need to run npm install
spec:
  params:
    - name: PATH_CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
  workspaces:
    - name: source
  results:
    - name: output
      description: Result of the task
  steps:
    - name: check
      image: docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
      script: |
      
        cd $(workspaces.source.path)

        checkForChangedFiles() {
            if [ -d node_modules ]; then
                echo "node modules folder detected."
                
                changedFiles=$(git log --pretty=oneline -1 --name-only | grep -E "package(-lock)*\.json")
                if [ -z $changedFiles ]; then
                    echo "no Changes to package.json found, updates dont't need to be installed"
                    exitFromTask 1
                else 
                    echo "Changes to package.json detected, updates need to be installed"
                    exitFromTask 0
                fi
            else
                echo "node modules not found, updates need to be installed"
                exitFromTask 0
            fi
            
        }

        exitFromTask() {
            if [ $1 == 0 ]; then
              printf "true" | tee $(results.output.path)
            else
              printf "false" | tee $(results.output.path)
            fi
            
            exit 0;
        }

        checkForChangedFiles
