apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ls-build-project
spec:
  workspaces:
    - name: source
  steps:
    - name: ls
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ['-c', 'ls $(workspaces.source.path)/build']