apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  params:
    - name: action
      description: Operation to be performed by npm
      default: "start"
      type: string
    - name: PATH_CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
  workspaces:
  - name: source
  steps:
    - name: npm-build
      image: node:14
      command:
        - /bin/sh
        - -c
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      args:
        - npm $(params.action)