apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task-with-condition
spec:
  steps:
    - name: ls
      image: alpine
      script: |
        echo "this is a simple task with condition"