apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app-pipeline
spec:
  params:
    - name: git-repo
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: git-clone
      taskRef:
        name: task-git-clone
      workspaces:
        - name: source
          workspace: pipeline-ws
      params:
      - name: url
        value: $(params.git-repo)
    - name: npm-install
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-ws
      runAfter:
        - git-clone
      params:
        - name: PATH_CONTEXT
          value: hello-world-example
        - name: action
          value: install
    - name: lint
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-ws
      runAfter:
        - git-clone
        - npm-install
      params:
        - name: PATH_CONTEXT
          value: hello-world-example
        - name: action
          value: run lint
    - name: test
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-ws
      runAfter:
        - git-clone
        - npm-install
      params:
        - name: PATH_CONTEXT
          value: hello-world-example
        - name: action
          value: run test
    - name: build
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-ws
      params:
        - name: PATH_CONTEXT
          value: hello-world-example
        - name: action
          value: run build
      runAfter:
        - git-clone
        - npm-install
    - name: ls-build-project
      taskRef:
        name: ls-build-project
      workspaces:
      - name: source
        workspace: pipeline-ws
      runAfter:
        - git-clone
        - npm-install
        - lint
        - test
        - build

