apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: npm-install-condition
spec:
  params:
    - name: context
      type: string
  resources:
    - name: source
      type: git
  check:
    image: alpine
    script: |
      cd $(resources.source.path/params.context)
      changedFiles="$(git diff --name-only HEAD@{1} HEAD)"

      checkForChangedFiles() {
          if [ -d node_modules ]; then
              echo "$changedFiles" | grep -E --quiet "package(-lock)*\.json" && eval packageJsonHasChanged
              exit 1
          else
              exit 0
          fi
          
      }

      packageJsonHasChanged() {
          echo "Changes to package.json detected, installing updates"
          exit 0
      }

      checkForChangedFiles
